name: Deploy to SiteGround
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to SiteGround
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USERNAME }}
          key: ${{ secrets.SG_SSH_KEY }}
          passphrase: ${{ secrets.SG_PASSPHRASE }}
          port: ${{ secrets.SG_PORT }}
          script: |
            cd www/findthinger.lantrev.com/public_html
            git pull origin main
            echo "Deployed successfully"
